version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sportapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportapp_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"

