services:
  postgres:
    image: postgres:latest
    container_name: sportapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportapp_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./users.csv:/var/lib/postgresql/data/users.csv
      - ./events.csv:/var/lib/postgresql/data/events.csv
    ports:
      - "5430:5432"
